# Generated by Django 4.2.16 on 2024-10-06 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0002_team_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='prospective_members',
            field=models.ManyToManyField(related_name='team_applications', to='sportify.user'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='sportify.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='sportify.user')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='messages',
            field=models.ManyToManyField(to='sportify.message'),
        ),
    ]
