# Generated by Django 4.2.16 on 2024-10-06 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0004_user_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auth_user',
        ),
    ]
