# Generated by Django 4.2.16 on 2024-10-08 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0005_remove_user_auth_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_PMA_administrator',
            field=models.BooleanField(default=False),
        ),
    ]
