# Generated by Django 4.2.16 on 2024-10-12 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0006_user_is_pma_administrator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_PMA_administrator',
            new_name='is_pma_administrator',
        ),
    ]
