# Generated by Django 4.2.16 on 2024-10-12 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0007_rename_is_pma_administrator_user_is_pma_administrator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_pma_administrator',
        ),
    ]
