# Generated by Django 4.2.16 on 2024-10-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0008_remove_user_is_pma_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_pma',
            field=models.BooleanField(default=False),
        ),
    ]
