# Generated by Django 5.1.1 on 2024-10-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0009_user_is_pma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='messages',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
