# Generated by Django 5.1.1 on 2024-10-30 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0010_remove_team_messages_delete_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='sportify.user')),
                ('team', models.ForeignKey(default='aassdsdafdafasa', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='sportify.team')),
            ],
        ),
    ]
