# Generated by Django 4.2.16 on 2024-11-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0012_user_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='associated_sport',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
