# Generated by Django 4.2.16 on 2024-11-17 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0013_team_associated_sport'),
        ('sportify', '0014_user_google_pfpurl_delete_userprofile'),
    ]

    operations = [
    ]
