# Generated by Django 4.2.16 on 2024-11-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0015_merge_20241117_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='No bio provided.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, default='Charlottesville, VA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='Not set.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='Not set.', max_length=10, null=True),
        ),
    ]
