# Generated by Django 5.1.1 on 2024-12-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportify', '0017_alter_user_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
